// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = "https://sbscowwgmokkbbzwllqs.supabase.co";
export const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNic2Nvd3dnbW9ra2JiendsbHFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA4OTA5ODQsImV4cCI6MjA4NjQ2Njk4NH0.tcnvFqENYEu20lRCUHzby3N-xI4n538naNZahQVIyBk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_ANON_KEY, 
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);